package top.guoxy.recruit.model;

import java.io.Serializable;

public class Comment implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.freshman_id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private Integer freshmanId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.freshman_id
     *
     * @return the value of comment.freshman_id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public Integer getFreshmanId() {
        return freshmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.freshman_id
     *
     * @param freshmanId the value for comment.freshman_id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setFreshmanId(Integer freshmanId) {
        this.freshmanId = freshmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment
     *
     * @return the value of comment.comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment
     *
     * @param comment the value for comment.comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment;
    }
}