package top.guoxy.recruit.model;

import java.io.Serializable;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pwdhash
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private String pwdhash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.department
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.jobposition
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private String jobposition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.truename
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pwdhash
     *
     * @return the value of user.pwdhash
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public String getPwdhash() {
        return pwdhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pwdhash
     *
     * @param pwdhash the value for user.pwdhash
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setPwdhash(String pwdhash) {
        this.pwdhash = pwdhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role
     *
     * @return the value of user.role
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role
     *
     * @param role the value for user.role
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.department
     *
     * @return the value of user.department
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.department
     *
     * @param department the value for user.department
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.jobposition
     *
     * @return the value of user.jobposition
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public String getJobposition() {
        return jobposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.jobposition
     *
     * @param jobposition the value for user.jobposition
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setJobposition(String jobposition) {
        this.jobposition = jobposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.truename
     *
     * @return the value of user.truename
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.truename
     *
     * @param truename the value for user.truename
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }
}