package top.guoxy.recruit.dao;


import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import top.guoxy.recruit.dto.CommentCountDto;
import top.guoxy.recruit.model.Comment;

import java.util.List;

@Mapper
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    Comment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Mon Feb 10 13:27:08 CST 2020
     */
    int updateByPrimaryKey(Comment record);

    @Select("select freshman_id, count(1) as count from comment where freshman_id = #{freshmanId}")
    @Results({
            @Result(property = "FreshmanId", column = "freshman_id"),
            @Result(property = "commentCount", column = "count")
    })
    CommentCountDto getCommentCount(Integer freshmanId);

    @Select("select * from comment where freshman_id = #{freshmanId}")
    List<Comment> getCommentsByFreshmanId (Integer freshmanId);
}